### ISSUE TITLE
Проблемы после деплоя

### ISSUE THREAD

**Issue by winlex** [winlex/calendar-techsup#47]
После нового деплоя происходит конфликт куки.

**Comment by winlex** [comment]
events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeError: request.clearCookie is not a function
at /app/server.js:44:19
    at /rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/google-spreadsheet/2.0.6/node_modules/google-spreadsheet/index.js:304:7
    at /rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/google-spreadsheet/2.0.6/node_modules/google-spreadsheet/index.js:166:15
    at Parser.<anonymous> (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/xml2js/0.4.19/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/xml2js/0.4.19/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/sax/1.2.4/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/sax/1.2.4/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/sax/1.2.4/node_modules/sax/lib/sax.js:889:7)

**Comment by winlex** [comment]
events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeError: request.clearCookie is not a function
at /app/server.js:44:19
    at /rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/google-spreadsheet/2.0.6/node_modules/google-spreadsheet/index.js:304:7
    at /rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/google-spreadsheet/2.0.6/node_modules/google-spreadsheet/index.js:166:15
    at Parser.<anonymous> (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/xml2js/0.4.19/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/xml2js/0.4.19/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/sax/1.2.4/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/sax/1.2.4/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/rbd/pnpm-volume/51b82c73-a4e7-4dbb-827e-93b1c2bac969/node_modules/.registry.npmjs.org/sax/1.2.4/node_modules/sax/lib/sax.js:889:7)

**Comment by winlex** [comment]
Проблема начала появляться уже не только после деплоя, а и просто при заходе первый раз на сайт.
Нужно продебажить проверку куки.
